---
title: "Merely Useful: Using R for Research Software Engineering"
author: 
- "Madeleine Bonsma-Fisher"
- "Kate Hertweck"
- "Damien Irving"
- "Luke Johnston"
- "Joel Ostblom"
- "Ian Flores Siaca"
- "Charlotte Wickham"
- "Greg Wilson"
documentclass: book
bibliography: includes/book.bib
csl: includes/jcb.csl
citation-package: none
link-citations: yes
github-repo: "merely-useful/r-rse"
favicon: favicon.ico
site: bookdown::bookdown_site
date: "`r Sys.Date()`"
lot: yes
lof: yes
---

# Welcome to the course webpage!

> It's still magic even if you know how it's done.
>
> — Terry Pratchett

TODO: Fill in this with a brief description on what course does, why its important, etc

Computers are now as essential for research as telescopes, test tubes, and libraries,
which means that researchers need need to know how to build, use, and share software.
However,
most introductions to programming focus on developing commercial applications,
not on exploring problems and answering questions.
This series of books will show you how to do the latter
both on your own and as part of a team.

The prequels to this book introduce three core skills:
how to write short programs to clean and analyze data in a reproducible way,
how to keep track of what you have done,
and how to share your software and your results with other people.
But just as some astronomers spend their careers designing telescopes,
some researchers focus on building software to make their colleagues' lives easier.
People who do this are called [research software engineers][rse],
and the aim of this book is to get you ready for this role—to help you go from writing code for your own use
to creating tools to help your entire field advance.

TODO: Update section? Needs revision.

For researchers and data scientists who can write functions to create programs that are several pages long,
and who want to be more productive and have more confidence in their results,
this book provides a pragmatic, tools-based introduction to research software engineering.
Unlike material courses aimed at computer scientists and professional software developers,
this book uses data analysis as a motivating example
and assumes that the learner's ultimate goal is to answer questions rather than ship products.


The course material was created using [rmarkdown] to write the lessons,
[bookdown] to create the book format, [GitHub] to host the [Git] 
repository of the material, and [GitHub Actions] to create the website.
The original source material for this course is found on the 
[`r-rse`] GitHub repository.

[rmarkdown]: https://rmarkdown.rstudio.com/
[bookdown]: https://bookdown.org/yihui/bookdown/
[GitHub]: https://github.com/
[Git]: https://git-scm.com/
[GitHub Actions]: https://github.com/features/actions
[`r-rse`]: https://github.com/merely-useful/r-rse

## Re-use and licensing {#licensing}

All of this material can be freely re-used under the terms of the
[Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
and the course code is licensed under a 
[MIT License](https://github.com/merely-useful/r-rse/blob/main/LICENSE-MIT.md),
so the material can be used, re-used, and modified, 
as long as there is attribution to this source.

## Target audience of book

TODO: Who is this book targeted towards? and why? and how can each use it.

While the learning content of this book targets the specific learning personas
described in FIXME, we wrote this book with three audiences in mind:

1. **Instructors** who would use this book as the basis for a course or workshop
of their own. Throughout the book there are sections dedicated to this reader
that give information or instructions on how to use or modify the material for
the instructors specific context.
2. **Learners in a class setting** who would be taking this course in a more
formal class or workshop setting that is lead by an instructor(s). Much of the
book is written with this reader in mind.
3. **Independent learners** who would be going through the material and learning
on their own. An independent learner can for the most part follow the book as if
they were a learner in a class setting, with some modifications that we highlight
and describe where necessary.

## Instructional design

The instructional design of the learning material contained in this book revolves
around three key concepts:

1. Participatory live-coding lessons, where participants join with instructors
to write and troubleshoot code step-by-step. We believe that this encourages
participants to actively engage with the material, to build muscle memory
through typing, and to learn how to handle mistakes, rather than passively
observing content.|
2. In-class and out-of-class exercises that includes independent reading of
assigned books 
|Participants read more concept-heavy content at their own
pace.|Including reading activities provides diverse learning opportunities aside
from listening skills, can be advantageous for non-native English speakers, and
can slow the pace of learning to enhance retention.|
|Completion of brief exercises|Exercises are interspersed throughout the live-coding sessions to complement the content.|Hands-on, practical exercises help reinforce what was previously learned and provides an opportunity to work through code at the learners' own pace.|
3. Project- and problem-based assignments that includes both  |Group assignment work|Participants collaborate with others to apply skills taught over the workshop in terms of cleaning, manipulating, analyzing, and visualizing data.|Helps to reinforce learning by applying the skills and knowledge to a new problem and task, thus building confidence in using the skills.|

## Acknowledgments

This book owes its existence to
everyone we met through [the Carpentries][carpentries].
We are also grateful to [Insight Data Science][insight] for sponsoring the early stages of this work
and to everyone who has contributed,
particularly Jonathan Dursi
and the authors of [@Nobl2009; @Hadd2010; @Wils2014; @Scop2015; @Tasc2017; @Wils2017; @Brow2018; @Deve2018; @Shol2019; @Wils2019].

```{r, child="./appendices/links.md"}
```

<!-- - Overview of material -->
<!--     - How to use, why to use, general details and overall description -->
<!--         - Reference "For Instructors" section for instructors to check out -->


  <!-- - Online books: [R Packages](https://r-pkgs.org/)  -->
  <!-- (we differentiate from this amazing book by structuring everything around  -->
  <!-- this being a course, with exercises, assessments, (group?) projects,  -->
  <!-- instructions/comments/notes for instructors, etc) -->
