# Course Syllabus {#syllabus}

TODO: Put learning outcomes, objectives, etc here from course-design.Rmd

This book covers the tools and practices needed to create work that is open, reproducible, and sustainable.
You can use this book for self-study
or as the foundation of a one-semester course for graduate students or senior undergraduates.
By its end,
you will be able to:

-   Use [branches][branch] to coordinate development of complex software.
-   Enable users to configure software without modifying it.
-   Re-run analyses and rebuild packages reproducibly with a single command.
-   Test your software and know which parts have not yet been tested.
-   Keep track of what still needs to be done and who's working on it.
-   Work on remote computers such as computing clusters or the cloud.
-   Document software so it can be easily used, maintained, and extended.
-   Create packages that can be installed in standard ways and be used by others.
-   Work productively in a small team where everyone is welcome.

## Learning outcomes

- **Learning outcome/goal**: Ultimately, to be able to create an R package, that:
    - Passes checks and requirements to (potentially) be submitted to CRAN
    - Incorporates best practices in package development 
    (unit testing, continuous integration, version control)
    - Has code that is written and developed in a readable, clean, and
    style-guide consistent format, so others can more easily read it
    - Is designed to involve the community, such as gaining potential contributors
    (including licensing, code of conduct, contributing guidelines, 
    well described README)
    - Has user-friendly (i.e. targeted to a novice to intermediate user)
    documentation and tutorials on how to use the package (e.g. a nice website)
    - Is adequately structured to make package management and maintenance easier
    (e.g. with Issue Templates, Project Boards, Labels, contributing guidelines)

## Who are these lessons for? {#rse-intro-personas}

Amira
:   completed a master's in library science five years ago
    and has since worked for a small aid organization.
    She did some statistics during her degree,
    and has learned some R and Python by doing data science courses online,
    but has no formal training in programming.
    Amira would like to tidy up the scripts, data sets, and reports she has created
    in order to share them with her colleagues.
    These lessons will show her how to do this and what "done" looks like.

Jun
:   completed an [Insight Data Science][insight] fellowship last year after doing a PhD in Geology
    and now works for a company that does forensic audits.
    He uses a variety of machine learning and visualization packages,
    and would now like to turn some of his own work into an open source project.
    This book will show him how such a project should be organized
    and how to encourage people to contribute to it.

Sami
:   became a competent programmer during a bachelor's degree in applied math
    and was then hired by the university's research computing center.
    The kinds of applications they are being asked to support
    have shifted from fluid dynamics to data analysis;
    this guide will teach them how to build and run data pipelines
    so that they can pass those skills on to their users.

### Prerequisites

Learners must be able to:

-   Write reusable functions to analyze tabular data using [R][r].
-   Keep track of their work using [Git][git] and [GitHub][github].
-   Create reproducible reports using [R Markdown][r-markdown].
-   Publish those reports with appropriate metadata such as a [DOI][doi] and [ORCID][orcid].

Learners will need:

-   A personal computer with Internet access.
-   A [Unix shell][unix-shell] (see Appendix \@ref(install) for how to set this up on Windows).
-   [R][r] and [RStudio][rstudio].
-   A [GitHub][github] account.

If you are using Windows,
please install [Chocolatey][chocolatey]:
you can use it to install other programs as you go along.

## What's the big picture? {#rse-intro-big-picture}

To make sense of what follows,
we must distinguish two key ideas:

-   [Open science][open-science]
    focuses on making data, methods, and results freely available to all
    by publishing them under [open licenses][open-license].
-   [Reproducible research][reproducible-research]
    means ensuring that anyone with access to data and software can feasibly reproduce results,
    both to check them and to build on them.

People often conflate these terms,
but they are distinct:

-   If you share your data and the programs that analyze it,
    but don't document what steps to take in what order,
    your work is open but not reproducible.
-   If you completely automate your analysis,
    but your data is only available to people in your lab,
    your work is reproducible but not open.

The third key idea is [sustainability][sustainable-software].
Software is sustainable if it's easier for people to maintain it and extend it than to replace it.
However,
sustainability isn't just a property of the software:
it also depends on the skills and culture of its users.
If a software package is being maintained by a couple of post-docs
who are being paid a fraction of what they could earn in industry
and have no realistic hope of promotion because their field doesn't value tool building,
it doesn't matter whether the package is well tested and easy to install:
sooner or later (probably sooner)
it will become [abandonware][abandonware].

### Why isn't all of this already normal?

Nobody argues that research should be irreproducible or unsustainable,
but "not against it" and actively supporting it are very different things.
Academia doesn't yet know how to reward people for writing useful software,
so while you may be thanked,
the effort you put in may not translate into job security or decent pay.

And some people still worry that if they make their data and code generally available,
someone else will use it and publish a result they have come up with themselves.
This is almost unheard of in practice,
but that doesn't stop people using it as a scare tactic.
Other people are afraid of looking foolish or incompetent by sharing code that might contain bugs.
This isn't just [impostor syndrome][impostor-syndrome]:
members of marginalized groups are frequently judged more harshly than others,
so being wrong in public is much riskier for them.

## Recommended schedule

TODO: Put here or put in "Instructions to instructors" section?

## Overview of packages built throughout course

- Overview of the (3-4?) packages developed throughout course:
    - Zipf's Law package: Used as key example for code-along, content, and most
    exercises.
    - Individual-based, small and simple package: Used as the first main "deliverable"
    for the course. Due after Build Management, with potential milestones due
    every 1-2 chapters. Final chapter exercises could be focused on completing the
    and working towards milestones and deliverable.
    - Individual-based, small improvements to existing package: Used as second 
    deliverable, due after "Community involvement". Should only build off of
    and improve an existing package, so doesn't need many milestones. Used to
    reinforce importance of having documentation that can involve the community.
    Could be the final exercises of chapters between Build Management and 
    Community Involvement.
    - Group-based, larger package: Optional, best used in longer length,
    class-based courses where groups can be formed. Is third and final
    deliverable. No need to have final exercises for this, instructor can decide.
    

## Key resources used

- Key resources to use for this:
  - R packages: usethis, devtools, pkgdown, testthat, styler, rmarkdown
  - Online books: [R Packages](https://r-pkgs.org/) 
    - We use the R Packages book as a reference

## Chapters outline

Course chapters and content need to be strongly aligned with learning outcome/goal.
Here is a draft outline to guide development.

1. Syllabus
    - Overview of course
    - Why to learn it and learning outcomes
    - Intended learner (personas, assumptions and expectations etc)
    - What makes this course different
        - Go over the "Whole Game" chapter of the R Packages book (https://r-pkgs.org/whole-game.html)
        to give an idea of what it all looks like in the end of this course

2. Folder and file structure (RStudio R Projects)
    - File paths, very basics of the shell (in RStudio)
    - Working directory and how it is set with RStudio R Projects
    - Making use of the fs package for filesystem management
    
3. Setting up an R package
    - Describing what a package is and when or why to make one
    - Using devtools, usethis for development
        - e.g. `use_devtools()` and `use_usethis()`.
    - Developing functions
        - Basic explanation of what a function is and its components
        - Actual process of taking code and converting it into a function will
        be done in next chapter
    - Making and using datasets
        - Downloading zipf data at this point, using `usethis::use_data_raw()`, write the script to download the data and process into `data/` via `usethis::use_data()`.

4. Function development in a package environment
    - Process of creating non-function code, checking that it works, then
      converting it into a function
        - There are several workflows for this (create in vignette Rmd, make a dev/creating.R
        script as a development location, developing in the examples Roxygen
        section, "Untitled1.R"). Which to use?
            - Mostly *how workflow actually looks like*.
    - Building functions up slowly, making small targeted functions that build up
    into a bigger more complex functions
    - Process control (if-else, stop, return, switch)
    - Dependency management
    - Function documentation (with roxygen2), part 1
        - To use `@examples` to help with creating function

5. Version control: Using Git and GitHub as a sole user (part 1)
    - Using Git in RStudio (standard add-commit-history)
    - Using Git in the Terminal of RStudio (moving in history with checkout,
    creating branches, adding and updating remotes)
    - Setting up GitHub for R package (make use of usethis), pushing and pulling
        - E.g. with pr_* functions from usethis
    - Emphasize exercises to practice, not showing output of git in code chunks (they are a pain to edit afterwards)

6. Checking correctness of code
    - Using basic debugging strategies ("breakpoints", simple `print()` or `stop()` calls, `debug()`, `browser()`)
    - Unit test (with testthat)
    - Code coverage (with covr)
    - With devtools

7. Build management and workflow
    - With devtools
    - Running local CRAN checks
    - General workflow (load_all, test, check)
    - Pre-push running test, build, and check
    - Continuous integration using GitHub Actions 

8. Developing documentation and tutorials on usage
    - Vignettes, README (with rmarkdown and usethis)
    - Function documentation (with roxygen2), part 2
    - Running spell checks and styling (with spelling and styler)

9. Exposing your package to the world with a website:
    - Setting up a website (with pkgdown)
    - Customizing the themes
    - Getting all resources and material organized
    - Defining lifecycle of your package and individual functions (with lifecycle)

10. Involving the community:
    - Designing your package to be used by or contributed to from the community
    (refer to Mozilla Science Labs Open Leaders material)
    - Contributing guidelines 
    - Being inclusive (code of conduct)
    - Licensing
    - Governance
    - NEWS file
    - reprex?

11. Version control: Workflows around using GitHub (part 2)
    - Make use of R builtin tools like the usethis pull request helpers 
    (and learning how to make use of this yourself)
    - Using this workflow as a team or as a contributor

12. Project management of your package development (either sole or in a team)
    - Issue tracking
    - Labeling
    - Project boards
    - Milestones

13. Preparing for package release
    - Check builds on other systems (with rhub)
        - Etiquette for using (mostly free) servers and external build systems like GitHub Actions and rhub (e.g. don't overuse them)
    - Managing your versions, git tagging

14. R package development in a team-based environment
    - Making use of GitHub Organizations/Teams
    - Branch protection, member roles
    - Resolving conflict, personality differences
    - Running meetings, code of conduct
    - Decision making
    - Governance
    - Issue assignment
    - Relying on and using code of conduct to build culture and standards
    - Setting up SSH, two-factor authentication, PATs?

- Appendices (ideas)
    - Other uses of packages
        - RStudio addins, snippets, rmarkdown templates, templates
        - rstudioapi
    - Template of Code of Conduct for participating in course
    - Instructions to potential instructors
    - Solutions
    - Glossary
    - References
