# Build management and workflow {#build-management}

- With devtools
- Running local CRAN checks
- General workflow (load_all, test, check)
- Pre-push running test, build, and check
- Continuous integration using GitHub Actions

## Learning Objectives 

* Describe the functionality devtools provides to manage an R package infrastructure
* Explain the CRAN checks' process and the different components
* Implement the workflow to validate an R package locally
* Deploy a GitHub Action that runs a continuous integration workflow

## Outline

* `devtools`

    * Text: First explain why you don't want to manage this manually
    * Text: Then explain how `devtools` addresses those pain points

* CRAN checks 

    * Text: Explain what is CRAN
        * I believe it isn't defined before in the book.
    * Text: Explain why CRAN needs "checks"
    * Text: Explain the importance of passing a CRAN check even if the package is not available on CRAN
    * Text: Explain what does CRAN look in when performing a check
    * Text: Explain the output of a CRAN check
    * Code: `devtools::check()`
    * Exercise: Present an error with CRAN check that has not been previously seen in the book and have the learners find the solution
      * This will be expanded in detail once all of the chapters have been outlined

CRAN, the Comprehensive R Archive Network (https://cran.r-project.org/) defines itself as:

> a network of ftp and web servers around the world that store identical, up-to-date, versions of code and documentation for R

What this means in practice is that CRAN is a package repository for R packages. 
As of March 2022, it contains over 19,000 of these packages. 
CRAN provides these packages as source code for Linux distributions and as compiled binaries for macOS and Windows. 
These compiled binaries substantially improve the speed of installation of the packages.
Now, as a package repository, CRAN has a policy to ensure that packages meet a certain level of quality before they are accepted into the repository. 
This policy is known as the CRAN Repository Policy. 
It is important to be familiar with the policy as it informs best practices and requirements about R package developement, even if your package is not going to be hosted in CRAN.
However, most folks don't try to comply with the policy manually and instead use a tool called a `check`. 

These checks verify that the package has:

- Tests
- Documentation
- Proper Metadata
- Dependency Tracking

among other things.

To-Do: Explain the output of a CRAN check


* R package build workflow

    * Text: Explain local functions and why to use `load_all()`
    * Text: Talk about tests and their purpose in the build process
    * Text: Explain the whole picture from document to load_all, tests and then check
    * Code: `devtools::load_all()` and `devtools::check()`

* Continuous Integration and GitHub Actions

    * Text: Explain what is continuous integration
    * Text: Explain GitHub Actions (https://github.com/features/actions)[https://github.com/features/actions]
    * Exercise: Deploy a sample GitHub Actions
      * Probably one that install R using the r-lib action is a good exercise
    * Code: `usethis::use_github_action_check_standard()`
    * Text: Explain how to navigate the result of the GitHub Action and the logs window

## Final exercise {#07-final-exercise}

Complete these tasks as part of the package for your first project assignment.
Refer to the project assignment TODO: Add ref to assignment here?
for more details. As with the other final exercises,
we will use the `kenyaweather` package as an example and reference.
Don't forget to add and commit any changes you've made into the Git history
after each task, and pushing to GitHub.

1. In your project package, check the package by running `check()` (with
`Ctrl-Shift-E` in RStudio). Do you have any notes, warnings, or errors from the
check?
2. Based on the check output, try to fix as many of the notes, warnings, and/or 
errors as possible. Usually `check()` provides informative enough messages that
help guide you to fixing the problems, but not always. Try as best you can.
3. Add a new function to you package by using `use_r()` that does TODO: Add something here?
4. Add roxygen2 documentation for the new function and then run `document()` 
(type `Ctrl-Shift-D` in RStudio).
TODO: This depends on if roxygen is talked about before or after this.
5. Load the function with `load_all()` (`Ctrl-Shift-L`) and see if the function works.
6. Create a new test for the function with `use_test()` and write a basic unit test
testing that the function produces the right output type (e.g. a data frame or vector).
Then run `test()` (`Ctrl-Shift-T`). Fix any errors or warnings that come up and
test again until you get no more errors or warnings.
7. Do another `check()` (`Ctrl-Shift-E`) and try to fix any notes, warnings, or
errors.
8. Set up your Git repository to use a GitHub Action that runs `check()` on
GitHub. Add this setup with `usethis::use_github_action_check_standard()`. Add
and commit this file, then push your changes up to GitHub. Go to the projects 
GitHub repository and check the Actions you just added.
