# Developing documentation and tutorials on usage {#package-documentation}

- Vignettes, README (with rmarkdown and usethis)
- Function documentation (with roxygen2), part 2
    - Markdown functionality with `usethis::use_roxygen_md()`
- Running spell checks and styling (with spelling and styler)

## Learning Objectives

* Describe the purpose of documenting code and packages
* Document functions with `roxygen`
* Create a README and vignette for package documentation
* Ensure that documentation is consistent with up-to-date style guidelines
using `styler`

## Outline

* Introduction: the purpose of documentation

  * Text: documentation is for collaborators, users, and future you. It is key
for openness, reproducibility, and sustainability.

* Documentation workflow: documenting the small stuff 
([R Packages reference](https://r-pkgs.org/man.html?q=roxygen#man))

  * Text: why document functions
  * Code: function documentation cycle. Add `roxygen` comments (with cursor in
function definition, do `Code > Insert roxygen skeleton` in RStudio). Run
`devtools::document()`. Include a deliberate typo here that will get caught by
`spelling` later in the chapter?
  * Exercise: add `roxygen` comments to two functions in the `zipfs` package.
  * Text: documenting tests
  * TODO: Decide if this is needed based on what is put into chapter 6.
  * Code: FIXME test documentation workflow
  * Exercise: add and/or improve comments and documentation in a test file in
the `zipfs` package.

* The README

  * Text: basic components of a README (description, installation instructions,
usage, examples)
  * Code: `usethis::use_readme_rmd()` - creates an R markdown document with
some boilerplate sections and text.
  * Code: `knitr` to knit README for previewing
  * Exercise: read the help file for `use_readme_rmd()` and `use_readme_md()`.
What is the difference between `.Rmd` and `.md` files? Why might one or the
other be better for a README?
  * Exercise: run `use_readme_rmd()` to create a README for the `zipfs` project
(if this isn't done in the previous code section). Edit `README.Rmd` to include
a description of `zipfs`, installation instructions, and an example of its use.
Knit the `README.Rmd` file so it creates a `README.md` file.

* Vignettes

  * Text: vignettes focus on the purpose and usage of a package or package
component, a long-form description of something the package does, with examples.
  * Code: `browseVignettes()` and `browseVignettes("packagename")`
  * Exercise: find the vignette(s) for the packages `devtools` and `ggplot2`.
Why might a package have more than one vignette? In what ways is a vignette
different from a README?
  * Code: `usethis::use_vignette("zipfs", title = "Using zipfs")`
  * Code: `knitr` to preview vignette
  * Exercise: run `use_vignette("zipfs", title = "Using zipfs")` to create a
template vignette. Modify the vignette to include a one-paragraph description
of the purpose of `zipfs`, and an example of how to use the `zipfs` functions
together to analyze a book. Run `knitr` to preview the vignette.

* `styler` and `spelling`: helpful packages for consistent and accurate
documentation and code

  * Text: What style guides are, style guide choices (tidyverse, [Google's R
style guide](https://google.github.io/styleguide/Rguide.html), others?)
  * Code: `styler::style_pkg()`
  * Code: `spelling::spell_check_package()`
  * Exercise: run `style_pkg()` to restyle the files in the `zipfs` package.
  * Exercise: run `spell_check_package()` to check the spelling in the `zipfs`
documentation files. Run `update_wordlist()` to add any special words to the
spell-checker that you want to ignore.

## Why do we need documentation? {#introduction}

Just like version control tracks what changes you make and why, documentation for code and packages tells your collaborators, your package's users, and future you *what* the code does and *why*.

Over time, programming languages have become more "human-readable": it is possible for an experienced programmer to read code and understand what it does. But even if one understands *what* a chunk of code is doing, it may not be obvious at all *why* it does that! Programming languages come with built-in ways to add comments and documentation that are not read by the computer, but exist solely to help you and your collaborators describe and understand code. Good documentation is key for openness, reproducibility, and project sustainability.

Good documentation happens at all scales of code: at the level of individual objects, functions, and tests as well as for the entire package. In this chapter, we describe the workflow of documentation alongside package development and outline the components of a well-documented package.

Reference: ([R Packages reference](https://r-pkgs.org/man.html?q=roxygen#man))

## Documenting functions and tests with `roxygen` {#function-documentation}

In R, documentation files for objects are stored by default in the `man/` folder in your package directory with a `.Rd` extension. These help files can be accessed for an object, function, or package by typing `?object-name` or `help(object-name)`.

## Final exercise {#08-final-exercise}

Complete these tasks as part of the package for your first project assignment.
Refer to the project assignment TODO: Add ref to assignment here?
for more details. As with the other final exercises,
we will use the `kenyaweather` package as an example and reference.
Don't forget to add and commit any changes you've made into the Git history
after each task, and pushing to GitHub.

1. Add the ability to write your roxygen2 documentation using Markdown with 
`usethis::use_roxygen_md()`.

2. Go through your existing function documentations and fill them in more.
Especially focus on completing the `@param`, `@return`, and `@examples` fields.
Then run `document()` (`Ctrl-Shift-D`).

3. Create a README file for your repository by using `use_readme_rmd()`.
    - Edit the `README.Rmd` to include a description of your package and its
    purpose, installation instructions, and one or more examples of how to use it.
    - Knit the `README.Rmd` file so it creates a `README.md` file.

4. Add a vignette to your project package by running `use_vignette("YOURPACKAGENAME")`,
replacing `YOURPACKAGENAME` with the name of your actual project package.
Edit the vignette to include a:
	- Higher-level paragraph describing your package and its purpose.
	- An example of how to use your package, including code, that's more complete
	than what the README might have.
    - Use `knitr` to Knit and preview your vignette.

4. (*Alternate*) Add a vignette to your project that describes how your package
interacts with another published R package. <!--leaflet?-->
    - Use `knitr` to Knit and preview your vignette.

5. Check the spelling and style of your files in your package by running
`styler::style_pkg()` to restyle your files and `use_spell_check()` to check the
spelling. Fix any problems and if there are any special words, create a
new file in `inst/WORDLIST`, add the word, and run `spelling::update_wordlist()`.
Then re-run these styling and spelling checks to confirm no problems exist anymore.
