# Version control: Workflows around using GitHub (part 2) {#github-workflows}

- Make use of R builtin tools like the usethis pull request helpers
  (and learning how to make use of this yourself)
- E.g. with pr_* functions from usethis
- Using this workflow as a team or as a contributor

## Final exercise {#11-final-exercise}

Complete these tasks as part of the package for your first project assignment.
Refer to the project assignment TODO: Add ref to assignment here?
for more details. As with the other final exercises,
we will use the `kenyaweather` package as an example and reference.
Don't forget to add and commit any changes you've made into the Git history
after each task, and pushing to GitHub.

1. Create a new Issue on your package's GitHub repository about an idea for a
function or to fix an existing function (you don't have to actually fix it).
2. Using the `pr_*` helpers, create a new branch called `fixing-function` using
`pr_init("fixing-function")`.
    - Make the following changes to the FIXME function:
        - FIXME: Not really sure what to say here. Could indicate that instructor has more detailed instructions. OR maybe not. Let's come back to this.
    - Add and commit these changes.
5. Push the changes up to GitHub by using `pr_push()`.
    - Create a new Pull Request based on the push in the newly opened up GitHub
    page (this should open automatically with `pr_push()`).
    - Merge the newly created Pull Request.
6. In your local Git repository, run `pr_finish()` to finish up.

Repeat this process one more time by making changes to:

- FIXME: Adding to README maybe or one of the vignettes?

### Exercises for second project assignment?
