# Project management of your package development (either solo or in a team) {#project-management}

- Project [roadmaps][project-roadmap]
- Issue tracking
    - These can range from simple project improvements (like scanning for typos in the README) to complex feature additions or bugs to be fixed.
- Labeling
    - Labels should make sense for your project, i.e. good first bug, discussion, help wanted, documentation, feature, etc. 
- Project boards
    - If you prefer GitHub Projects, create a GitHub Project for your package. Organize your issues from left to right in some version of "to-do", "in-progress", and "complete".
- Milestones

## Learning objectives

* Use GitHub issues, issue labels, and roadmaps to coordinate project tasks and goals
* Create GitHub Projects and GitHub Milestones for long-term project management
* Explain the purpose of Projects and Milestones and when to use each

## Outline

<!-- We have a choice about the order of presenting this material: should we start at the top, with high-level project management, and then go over the components (i.e. GitHub projects / milestones -> roadmap -> issues) or should we start small with issues and build up to their combined uses for project management? Issues as bug reports and feature requests from the community are now covered in chapter 10; here we get into issue categorization, labeling, and milestones and project boards.-->

- Project management with GitHub Issues
  - Text: Beyond bugs: how GitHub issues can help you keep track of tasks and communicate with your community ([reference](https://mozilla.github.io/open-leadership-training-series/articles/get-your-project-online/project-set-up-for-collaboration-with-github/#project-structure-and-organization)). How to label issues and link issues to other parts of your project.
  - Exercise: create at least three issue labels for the `zipfs` repository. Label the existing issues so that each has at least one label.

- Planning and managing your project's goals
  - Text: [Roadmaps](https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/), GitHub Projects, and Milestones are all ways to keep track of the big-picture goals and progress of your project on GitHub.
  - Exercise: create a roadmap for the `zipfs` project, either as an issue or as a file called ROADMAP.md.
  - Exercise: create several new issues for the `zipfs` project using the roadmap as inspiration. Add labels to these issues.
  - Exercise: look at some examples of packages that use GitHub milestones and GitHub Projects. Are there situations in which one project management approach is better than the other?
    - Milestone examples:
        - [ggplot2](https://github.com/tidyverse/ggplot2/milestones)
	      - FIXME: more examples?
    - Project examples:
        - [bootstrap](https://github.com/twbs/bootstrap/projects)
	      - FIXME: more examples?
  - Exercise: create a GitHub Project for the `zipfs` repo containing the columns "To do", "In progress", and "Done".
  - Exercise: create a milestone using the roadmap as inspiration. Assign at least two issues to the milestone.
  - Exercise: in the `zipfs` roadmap, add links to the issues you created based on the roadmap and a link to the milestone.

[project-roadmap]: https://mozilla.github.io/open-leadership-training-series/articles/opening-your-project/start-your-project-roadmap/

<!-- TODO: This is better here, not in the final exercise. -->
<!-- Example: [STEMMM Role Models -->
<!-- roadmap](https://github.com/KirstieJane/STEMMRoleModels/issues/1). -->

- use_github_labels(), browse_github_issues(), issue_reprex_needed(), and perhaps issue_close_community()
- Give set of recommended labels?
- Issue templates? (made by Joel: https://github.com/altair-viz/altair/issues/new/choose)

## Final exercise {#12-final-exercise}

Complete these tasks as part of the package for your first project assignment.
Refer to the project assignment TODO: Add ref to assignment here?
for more details. As with the other final exercises,
we will use the `kenyaweather` package as an example and reference.
Don't forget to add and commit any changes you've made into the Git history
after each task, and pushing to GitHub. Make use of the usethis `pr_*` workflow
described in Chapter \@ref(github-workflows).

1. Create a [roadmap][project-roadmap] for your project describing short-term,
medium-term, and long-term project goals. For now keep these goals about completing
the first project assignment. This can be a GitHub issue or a file called
`ROADMAP.md`. TODO: We should decide on one, to restrict learners choice.

2. Using your roadmap as inspiration for todo items, create new Issues for a few
of your project's tasks.
    - Create several new Issue Labels. GitHub provides a few good default ones.
    Add some new ones like FIXME: Add specific labels here, other than the ones
    that github makes.
    - Add a link in your `CONTRIBUTING.md` to Issues with the label `good-first-issue`
    so new contributors know where they can get started.
    - In your roadmap, add links to relevant Issues for others (and yourself)
    to be able to quickly find and look over.

TODO: This exercise might be more appropriate as a core exercise of this chapter, rather than part of the final one.
3. Look at some examples of packages that use GitHub Milestones and GitHub Projects. Are there situations in which one project management approach is better than the other? Which do you prefer, or which do you feel suits your project better?
    - Milestone examples:
        - [ggplot2](https://github.com/tidyverse/ggplot2/milestones)
	- FIXME: more examples?
    - Project examples:
        - [bootstrap](https://github.com/twbs/bootstrap/projects)
	- FIXME: more examples?

4. Depending on whether you prefer Milestones or Projects, create one for your
project for finishing this first project assignment. 

### Exercises for second project assignment?
