# Team-based development {#team-package-dev}

TODO: Decide if this should be a chapter covered by solo learner and if so, how?

## Learning objectives

- To learn about and apply tools within GitHub for improving team work and
coordination on developing an R package in a team-based environment.
- To understand how explicitly stating culture and standards for behaving and
interacting with those in your team can help build a healthy and productive team
environment.

## Overview (remove this header later)

- Making use of GitHub Organizations/Teams, member roles
    - Text: 
        - Centralize team activity, more settings to control how team members
        contribute, more control for other members
        - Different roles and permissions of members ("owners", "maintainers", etc)
    - Exercise:
        - Solo: Create a new GitHub Organization and make a new (random?) repo 
        in the newly created Organization. (or move the package repo over into the
        Organization?)
        - Team: 
            - Discuss within your team who wants to be assigned the "owner" of
            the organization
            - One of the owners create a new GitHub Organization
            - Add the other team members and set their permission level to maintainer,
            (and owner if there will be more than one.)
            - Create new repo of the ... (FIXME: not sure which repo should be created)
- Setting up two-factor authentication
    - Text: What is it and why to use it.
    - Text: In general 2FA is highly highly encouraged, but on team-based projects,
    its even more so important, especially for repo owners and organization "owners".
    - Exercise: Set up 2FA for your GitHub account.
- Branch protection
    - Text: Used to assign a specific person or people to be responsible for specific
    branches, to provide a level of accountability and prevent unreviewed content
    from being added to package.
    - Text: Generally, depending on skill of member in git/github, best give
    more team members access to modifying branch than to have less. But ultimately
    it is a safety and accountability feature that needs to be discussed with team.
    - Exercise: 
        - Solo: In the Organization repo, set up branch protection for the main branch.
        - Team:
            - In the organization repo, set up branch protection for the main branch
            and assign the owners as the only ones who can push to the branch.
            FIXME: Make sure this is the correct terminology.
- Relying on and using code of conduct, contributing guide, governance to build
culture and standards
    - Text: An implicit team culture will naturally evolve as people work together,
    but having purely implicit cultural norms makes it difficult for newcomers
    and for dealing with problems that come from misunderstanding of these cultural
    practices. Much of this comes from the code of conduct and contributing guidelines,
    but there are other aspects that can be team-, country-, etc specific.
    - Exercise:
        - (Solo/team?): Brainstorm come explicit expected behaviours, norms, 
        practices that you would like in a team environment. Write this text
        down and put it in the (FIXME: where? governance? conduct?)
    - Text: Consider how a team might handle, prevent/limit, and resolving
    conflict and personality differences. These often are team-specific.
    - Exercise:
        - (Solo/team?): Brainstorm ideas for what things to write about and include
        in an explicit document about how these are handled.
- Running meetings
    - Where would text be about this? Contributing? Governance?
    - Text: Running effective meetings is a key skill to working as a team.
    - Text: List some best practices.
    - Exercise: 
        - Consider past meetings you've had. Think of the worse and best meetings.
        What made a good meeting? What made a bad one?
        - Team: Discuss and brainstorm as a team some practices you agree with 
        and want to implement in your meetings.
- Governance (team focused)
    - Text: Governance is being explicit about the structure of the team, who does
    what and is responsible for what, how decisions are made, etc.
    - Exercise:
        - Solo: ? FIXME: add something here?
        - Team: Discuss as a team how you want to make decisions, who is responsible 
        for what, etc. Write these decisions in the Governance file.
    - Text: A major advantage of using GitHub is the project management, like issue assignments.
    How to assign issues/tasks can be a challenge and depending on the size of the
    team, you might need someone dedicated to coordinating issue assignment etc.
    - Exercise:
        - Team: Discuss and write down who will have the role of coordinating issues/tasks
        to team members.
    - Text: CODEOWNERS (?) who is primarily responsible for what parts of the package
    (e.g. R code vs vignettes). Using this concept can help streamline and automate
    other tasks.
    - Have exercise here or too much?

<!--
TODO: revise this text when adding the actual content.
A team work contract communicates specifically **how** the core group of people who are working together
and gives more detail about the logistics of working together and the expectations you have for each other.
This document will govern your working relationship and if done correctly,
should help you manage and resolve any issues that arise.
MIT's online software construction course has [a good description of what to put in a team work contract](http://web.mit.edu/6.005/www/fa15/projects/abcplayer/team-contract/).
Some key aspects of the team work contract could be:

- How will work be distributed in a fair and equitable way?
- What are the expected work hours for the project? 
- How often will group meetings occur ([here is a nice article](http://third-bit.com/2018/05/11/meetings.html) on meetings)?
- Will you have meeting agendas and minutes? If so, what will be the system for rotating through these responsibilities?
- What will be the style of working?
    - Will you start each day with [stand-ups](https://www.atlassian.com/agile/scrum/standups), or submit a summary of your contributions 4 hours before each meeting? or something else?
- What is the quality of work each team member expects from themselves and each other?
- When are team members not available (e.g., evenings and Sundays because of family obligations).
- And any other similar things that govern your working relationships.

Use this opportunity to use your prior knowledge/experience to improve your teamwork, communication, leadership, and organizational skills.
You will need all of these for your capstone projects (and beyond)!

We recommend that generate the team work contract according to these guidelines

- For 5 minutes, each team member will silently write out 4 different suggestions for the team work contract on their computer.
- Next, paste all suggestions into a common Google doc (or similar)
  and arrange them to put similar suggestions together.
- Spend 10 -15 minutes discussing the suggestions
  and decide which ones you will use for your team contract either by consensus or voting
  (you can of course add new ones at this point if any were missed earlier)
- Add the final contract in a file called `team-contract.md` in the repo root
  (in organizations this file might be kept internal instead of committed to a public repo).
    - These are the principles you adhere to when working.
    - This file should only be updated if there is agreement between team members to do so.
-->

## Final exercises

<!-- NOTE: Preferably something linked to working towards completing the project assignments, maybe to be used as a milestone? -->

### For the first project assignment

These exercises are to be done on the *first project assignment* (the
individual-based one). You won't be able to practice everything that you've
learned during this chapter for this exercise.

1. Set up branch protection for your main branch in your package repository on
GitHub.
2. Create a file called `GOVERNANCE.md` (FIXME: Should this be here?) and write
some general guidelines on:
    - How decisions are made.
    - If and how meetings will be run and held.
    - What culture and standards are valued and how they will be shaped.
    - How conflict/disagreements will be resolved.
3. On your GitHub account, set up 2FA and SSH.
4. In your GitHub package repository settings, create a PAT for working with...
TODO: This item might already be done for setting up GitHub actions.

### For the third project assignment

These exercises are to be done for the *third, team-based project assignment*.

1. Assign one team member to create a GitHub Organization account. 
Have this team member add the other members to the Organization.
    - Set each team member with "Maintainer" permissions.
2. Assign another team member to create a new repository where the
project package will be hosted.
    - This team member will then set up branch protection of the main
    branch.
3. In the new repository, create a new file called `GOVERNANCE.md`.
As a group, decide on and write down:
    - How decisions will be made.
    - How meetings will be run.
    - How disagreements will be resolved.
4. As a group, decide on the tasks that need to be completed and
create Issues of those tasks. Together, assign which team member
will do which tasks.
